<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */
/*get_header();

	

		do_action( 'genesis_before_content' );
		genesis_markup( array(
			'html5'   => '<main %s>',
			'xhtml'   => '<div id="content" class="hfeed">',
			'context' => 'content',
		) );
			do_action( 'genesis_before_loop' );
			do_action( 'genesis_loop' );
			do_action( 'genesis_after_loop' );
		genesis_markup( array(
			'html5' => '</main>', //* end .content
			'xhtml' => '</div>', //* end #content
		) );
		do_action( 'genesis_after_content' );

	
	do_action( 'genesis_after_content_sidebar_wrap' );

	get_footer();*/
remove_action( 'genesis_entry_header', 'genesis_post_info',9 );
add_action( 'genesis_entry_header', 'genesis_post_info',10 );

get_header();
do_action( 'genesis_before_content_sidebar_wrap' );
	genesis_markup( array(
		'html5'   => '<div %s>',
		'xhtml'   => '<div id="content-sidebar-wrap">',
		'context' => 'content-sidebar-wrap',
	) );
//* This file handles pages, but only exists for the sake of child theme forward compatibility.
$content = get_the_content(); 
	$title = get_the_title(  );
	//$permalink=get_permalink(  );	
	$permalink=genesis_get_image(  array(  'format' => 'url', 'size' => 'full'   )   );
	$image = genesis_get_image(  array(  'format' => 'url', 'size' => genesis_get_option(  'image_size'  )   )   );
	
	echo '<div class="post_content">';
	do_action( 'genesis_entry_header' );

	do_action( 'genesis_before_entry_content' );
	printf( '<div %s>', genesis_attr( 'entry-content' ) );
	echo '<div class="media_container">';
		if($image){
	       printf(  '<a href = "%s" rel = "bookmark"><img class = "post-image" src = "%s" alt="" /></a>',  $permalink, $image   );
		}
	echo '</div>';
		genesis_do_post_content();
	echo '</div>'; //* end .entry-content
	do_action('genesis_after_entry');
	echo '</div>';
	do_action( 'genesis_after_content' );
	echo '</div>'; //* end .content-sidebar-wrap or #content-sidebar-wrap
do_action( 'genesis_after_content_sidebar_wrap' );

get_footer();